#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

# The version tag is passed as 1st argument by RPM %build scriptlet
my $version = shift;
# The release tag is passed as 2nd argument by RPM %build scriptlet
my $release = shift;

# Override DB sysconfig/Version prop:
if(defined $version) {
    $version =~ s/^(\d+)\.(\d+).*$/$1.$2/; # extract first two numbers
    open(my $fh, '>', 'root/etc/e-smith/db/configuration/force/sysconfig/Version') 
	|| die "Could not set version string $version\n";
    print $fh $version . "\n";
    close($fh);
}

# Override DB sysconfig/Release prop:
if(defined $release) {
    if ($release eq "1") { # if 1, print Final
	$release = "Final";
    } else {
        # if not 1, just print the substring before the first dot
	$release =~ s/([^\.]+).*/$1/;
	warn "RELEASE VERSION SET TO '$release'\n";
    }  
    open(my $fh, '>', 'root/etc/e-smith/db/configuration/force/sysconfig/Release') 
	|| die "Could not set release version $release";
    print $fh $release . "\n";
    close($fh);
}
